development:
  app_id: 7OFMk091CR4zL4lCrq8FexHcHyH6PZ52lySoUUuj
  master_key: Jfxa110kK6NT5d9i2yAaP6tNZxx04EMPxkxDhzxF

test:
  app_id: 7OFMk091CR4zL4lCrq8FexHcHyH6PZ52lySoUUuj
  master_key: Jfxa110kK6NT5d9i2yAaP6tNZxx04EMPxkxDhzxF

production:
  app_id: 7OFMk091CR4zL4lCrq8FexHcHyH6PZ52lySoUUuj
  master_key: Jfxa110kK6NT5d9i2yAaP6tNZxx04EMPxkxDhzxF

