development:
  app_id: 7OFMk091CR4zL4lCrq8FexHcHyH6PZ52lySoUUuj
  api_key: vJtExpXsFcA3noDJ2fTZbamEXp4kgcfMADbHfNlg
  master_key: Jfxa110kK6NT5d9i2yAaP6tNZxx04EMPxkxDhzxF
  host: http://112.196.26.153:9000
  path: parse

test:
  app_id: 7OFMk091CR4zL4lCrq8FexHcHyH6PZ52lySoUUuj
  api_key: vJtExpXsFcA3noDJ2fTZbamEXp4kgcfMADbHfNlg
  master_key: Jfxa110kK6NT5d9i2yAaP6tNZxx04EMPxkxDhzxF
  host: http://112.196.26.153:9000
  path: parse

production:
  app_id: 7OFMk091CR4zL4lCrq8FexHcHyH6PZ52lySoUUuj
  api_key: vJtExpXsFcA3noDJ2fTZbamEXp4kgcfMADbHfNlg
  master_key: Jfxa110kK6NT5d9i2yAaP6tNZxx04EMPxkxDhzxF
  host: http://112.196.26.153:9000
  path: parse

